// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omvpmpzapydnmstyebpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tdnBtcHphcHlkbm1zdHllYnBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ1OTc4MTYsImV4cCI6MjA4MDE3MzgxNn0.TscSKRG2IZApS39ppOFv0qDnh7mGkgNx-TymDIKmynE";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
